# Generated by Django 4.1.5 on 2023-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='chat_list',
            field=models.ManyToManyField(through='chat.UserChat', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
