# Generated by Django 4.1.5 on 2023-01-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_author_chat_list_message_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
