# Generated by Django 4.1.5 on 2023-01-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
