# Generated by Django 4.1.5 on 2023-01-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_author_chat_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pinned',
        ),
    ]
